### ISSUE TITLE
Bitte ein readme ergänzen mit erklärungen

### ISSUE THREAD

**Issue by rubo77** [eulenfunk/firmware#1]
im Readme sollte stehen, welche dateien hier wichtig sind, welche sites die aktivsten sind, was build.sh ungefähr tut,...

Und vor allem eine genaue anleitung, was man alles auschecken muss in welcher reihenfolge in welchen ordner, damit man das build.sh benutzen kann.

**Comment by petabyteboy** [comment]
Und noch eine Kugel Eis oben drauf? (scnr)

Ich hab angefangen das neu zu bauen auf https://git.pbb.lc/petabyteboy/firmware
Es muss ein Gluon-Repository neben der build.sh liegen, die Version ist egal, den Rest regelt das Script.

**Comment by rubo77** [comment]
warum habt ihr den master bei dem commit bb6ca6a342a5efcf602c01b4a44974e71b0e7f76 vom 20.5.2017 abgespalten?

**Comment by rubo77** [comment]
Dies ware die erklärung aus dem chat:

----


# welche branches auf http://images.ffdus.de/ sind wichtig?
broken, experimental und stable (das was anderswo "experimental" heisst ist hier "broken". Das was anderswo "beta" heisst ist hier "experimental". Einfach damit normale User die stable nutzen und nichts anderes)

- broken ist der updatekanal `experimental`, experimental der kanal `experimental` und stable ist kanal `stable`
- es gibt jeden releasekanal in "l2tp" und "fastd" (bei fastd entfällt der namenszusatz im Releasekanal)
- es gibt zusätzlich noch einen "Bau-Stand" "key" (z.B. stable/stablekey stablel2tp/stablel2tpkey) in der "bypassconfigmode" und mehrere ssh-keys gesetzt sind. Das ist kein eigener releasekanal, sondern nur einer der im Kaanl des eigentlichen "normalen ohne key" bleibt. Ist nur für sysupgrades/factorytftp. sysupgrade-images werden aber gebracht, "wenn man aus anderen communities via shell kommt".

# welche images werden gebaut?
alle 12 ebenfalls ( 2 vpntypes x 3 releasenames (nur 2 channel) x 2 keytypes) 

# "others"
sind nur Hilfeleistungen für andere communities derzeit (kann aber wieder kommen)

# build-aufruf

    ./build.sh sites.dusl2tp

wobei dann die sites.dus2ltp dann Zeilen enthält wie "experimentall2tp v2016.2.x dusl2tp dusl2tp". (Achtung, Zeile mit muss mit CR abgeschlossen sein, aber darf keine Leerzeilen enthalten.. ja, das ist blöd)

---
markdown:

```

# welche branches auf http://images.ffdus.de/ sind wichtig?
broken, experimental und stable (das was anderswo "experimental" heisst ist hier "broken". Das was anderswo "beta" heisst ist hier "experimental". Einfach damit normale User die stable nutzen und nichts anderes)

- broken ist der updatekanal `experimental`, experimental der kanal `experimental` und stable ist kanal `stable`
- es gibt jeden releasekanal in "l2tp" und "fastd" (bei fastd entfällt der namenszusatz im Releasekanal)
- es gibt zusätzlich noch einen "Bau-Stand" "key" (z.B. stable/stablekey stablel2tp/stablel2tpkey) in der "bypassconfigmode" und mehrere ssh-keys gesetzt sind. Das ist kein eigener releasekanal, sondern nur einer der im Kaanl des eigentlichen "normalen ohne key" bleibt. Ist nur für sysupgrades/factorytftp. sysupgrade-images werden aber gebracht, "wenn man aus anderen communities via shell kommt".

# welche images werden gebaut?
alle 12 ebenfalls ( 2 vpntypes x 3 releasenames (nur 2 channel) x 2 keytypes) 

# "others"
sind nur Hilfeleistungen für andere communities derzeit (kann aber wieder kommen)

# build-aufruf

    ./build.sh sites.dusl2tp

wobei dann die sites.dus2ltp dann Zeilen enthält wie "experimentall2tp v2016.2.x dusl2tp dusl2tp". (Achtung, Zeile mit muss mit CR abgeschlossen sein, aber darf keine Leerzeilen enthalten.. ja, das ist blöd)
```

**Comment by rubo77** [comment]
@petabyteboy : Ihr könnt ja auch noch eine sektion einbauen, wo ihr auflistet, wo alle firmwares gehostet werden:

- ffgl - Freifunk im Rheinisch-Bergischen Kreis - https://images.ffgl.eu.
- ff-dus - http://images.ffdus.de/
- ...

**Comment by petabyteboy** [comment]
Das entzieht sich ehrlich gesagt meiner Kenntnis abgesehen von ffgl. Es steht ja jedem frei die Images zu bauen und irgendwo zu hosten. Das selbe gilt auch für die Tags.
